bind-dns:
  # https://hub.docker.com/r/sameersbn/bind
  image: docker.io/sameersbn/bind:9.16.1-20200524
  dns: 127.0.0.1
  restart: always
  environment:
    - ROOT_PASSWORD=pichuang
  ports:
   - 10000:10000/tcp
   - 53:53/udp
   - 53:53/tcp
  volumes:
    - "./root:/data"
