version: "3"
services:
  mongo:
    # Ref: https://hub.docker.com/r/bitnami/mongodb
    image: docker.io/bitnami/mongodb:5.0.7
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_ROOT_USER: root
      MONGODB_ROOT_PASSWORD: root
    volumes:
      - "./root:/bitnami/mongodb"

  mongo-express:
    image: docker.io/library/mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
