version: "3"
services:
  db:
    image: docker.io/library/mariadb:10.4.21
    restart: always
    environment:
      # MYSQL_USER: test
      # MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    volumes:
      - "./root:/var/lib/mysql"
    ports:
      - 3306:3306
