version: "3"
services:
  mysql-bitnami:
    # Ref https://hub.docker.com/r/bitnami/mysql
    image: docker.io/bitnami/mysql:8.0.28
    restart: always
    environment:
      # MYSQL_USER: test
      # MYSQL_PASSWORD: test
      #MYSQL_ROOT_PASSWORD: root
      #MYSQL_DATABASE: testdb
      # ALLOW_EMPTY_PASSWORD is recommended only for development
      ALLOW_EMPTY_PASSWORD: "yes"
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mysql/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
    volumes:
      - "./root:/bitnami/mysql/data"
    ports:
      - 3306:3306
