version: "3"
services:
  redis:
    image: docker.io/library/redis:5.0.6
    restart: always
    command: redis-server
    ports:
     - 6379:6379
    volumes:
     - "./root:/data"
    environment:
     - REDIS_REPLICATION_MODE=master
     - ALLOW_EMPTY_PASSWORD=yes
