version: "3.2"
services:
  redis:
    image: "redis:alpine"
    command: redis-server
    ports:
     - "6379:6379"
    volumes:
     - "./root/redis-data:/var/lib/redis"
     - "./root/redis.conf:/usr/local/etc/redis/redis.conf"
    environment:
     - REDIS_REPLICATION_MODE=master
     - ALLOW_EMPTY_PASSWORD=yes
