version: "3"
services:
  prometheus:
    # Ref: https://hub.docker.com/r/bitnami/prometheus
    image: docker.io/bitnami/prometheus:2.34.0
    restart: always
    volumes:
      - "./root/data:/opt/bitnami/prometheus/data"
      - "./root/conf:/opt/bitnami/prometheus/conf"
    ports:
      - 9090:9090

  grafana:
    # Ref: https://hub.docker.com/r/bitnami/grafana/
    image: docker.io/bitnami/grafana:8.4.6
    restart: always
    volumes:
      - "./grafana_root/conf:/opt/bitnami/grafana/conf"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "bitnami"
      GF_RENDERING_SERVER_URL: "http://grafana-image-renderer:8080/render"
      GF_RENDERING_CALLBACK_URL: "http://grafana:3000/"
    ports:
      - 3000:3000

  grafana-image-renderer:
    image: docker.io/bitnami/grafana-image-renderer:3.4.2
    environment:
      HTTP_HOST: "0.0.0.0"
      HTTP_PORT: "8080"
      ENABLE_METRICS: 'true'
    ports:
      - '8080:8080'
